"""Phase 6 - origin determinations, shipment origin/destination country

Revision ID: 12b8650938f2
Revises: 6ebc055515aa
Create Date: 2026-08-22 19:21:38.239976

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b8650938f2'
down_revision: Union[str, None] = '6ebc055515aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origin_determinations',
    sa.Column('line_item_id', sa.UUID(), nullable=False),
    sa.Column('agreement', sa.String(length=255), nullable=True),
    sa.Column('qualifies', sa.Enum('QUALIFIES', 'DOES_NOT_QUALIFY', 'INSUFFICIENT_DATA', 'NOT_APPLICABLE', name='origin_qualification_status'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_duty_savings_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estimated_duty_savings_currency', sa.String(length=3), nullable=True),
    sa.Column('local_content_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_origin_determinations_line_item_id'), 'origin_determinations', ['line_item_id'], unique=True)
    op.add_column('shipments', sa.Column('origin_country', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('destination_country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'destination_country')
    op.drop_column('shipments', 'origin_country')
    op.drop_index(op.f('ix_origin_determinations_line_item_id'), table_name='origin_determinations')
    op.drop_table('origin_determinations')
    # ### end Alembic commands ###
