"""Phase 5 - permit requirements

Revision ID: 6ebc055515aa
Revises: 730401b658f0
Create Date: 2026-08-22 18:42:30.602066

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ebc055515aa'
down_revision: Union[str, None] = '730401b658f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_requirements',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('regulator', sa.String(length=100), nullable=False),
    sa.Column('permit_type', sa.String(length=255), nullable=False),
    sa.Column('applies_to_line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_processing_time_days', sa.Integer(), nullable=False),
    sa.Column('reference_link', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_requirements_shipment_id'), 'permit_requirements', ['shipment_id'], unique=False)
    # NOTE: autogenerate falsely detected ix_tariff_headings_embedding_cosine as
    # removed on every migration since Phase 3 — it was created via raw op.execute()
    # (pgvector HNSW isn't representable as a plain SQLAlchemy Index()), so
    # autogenerate can't see it in the ORM metadata and assumes it should be dropped.
    # Left alone here, same as the Phase 4 migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permit_requirements_shipment_id'), table_name='permit_requirements')
    op.drop_table('permit_requirements')
    # ### end Alembic commands ###
