"""Phase 4 - discrepancies

Revision ID: 730401b658f0
Revises: 9740c1c0de67
Create Date: 2026-08-22 18:07:22.427607

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '730401b658f0'
down_revision: Union[str, None] = '9740c1c0de67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrepancies',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKING', 'WARNING', 'INFORMATIONAL', name='discrepancy_severity'), nullable=False),
    sa.Column('documents_involved', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_resolution', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_shipment_id'), 'discrepancies', ['shipment_id'], unique=False)
    # NOTE: autogenerate falsely detected ix_tariff_headings_embedding_cosine as
    # removed — it was created via raw op.execute() in the Phase 3 migration (pgvector
    # HNSW isn't representable as a plain SQLAlchemy Index()), so autogenerate can't
    # see it in the ORM metadata and assumes it should be dropped. Left alone here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discrepancies_shipment_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    # ### end Alembic commands ###
