"""Phase 3 - tariff headings, line items, classification results

Revision ID: 9740c1c0de67
Revises: 8cee48128fc3
Create Date: 2026-08-22 14:15:56.044444

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9740c1c0de67'
down_revision: Union[str, None] = '8cee48128fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Not auto-generated — required before the vector column below can exist.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('tariff_headings',
    sa.Column('hs_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_headings_hs_code'), 'tariff_headings', ['hs_code'], unique=True)
    # Not auto-generated — HNSW index for cosine-distance vector search
    # (TariffKBRepository.vector_search). Fine to add even at a tiny seed-data scale;
    # it's what a real ingested schedule (thousands of rows) will need anyway.
    op.execute(
        "CREATE INDEX ix_tariff_headings_embedding_cosine ON tariff_headings "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('line_items',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_shipment_id'), 'line_items', ['shipment_id'], unique=False)
    op.create_table('classification_results',
    sa.Column('line_item_id', sa.UUID(), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_override_hs_code', sa.String(length=20), nullable=True),
    sa.Column('user_override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_classification_results_confidence_range'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_results_line_item_id'), 'classification_results', ['line_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_results_line_item_id'), table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index(op.f('ix_line_items_shipment_id'), table_name='line_items')
    op.drop_table('line_items')
    op.execute("DROP INDEX IF EXISTS ix_tariff_headings_embedding_cosine")
    op.drop_index(op.f('ix_tariff_headings_hs_code'), table_name='tariff_headings')
    op.drop_table('tariff_headings')
    # ### end Alembic commands ###
